eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
           
server:
  port: 8885
spring:
  application:
    name: microservices4
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/rentkaro
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
